# Generated by Django 4.2.6 on 2023-11-01 09:44
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from BankApp.models import Account



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_authenticated', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('SocSecNumber', models.IntegerField(unique=True, verbose_name=12)),
                ('FailedLoginCount', models.IntegerField(default=0)),
                ('IsBlocked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('CustomerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='TimeLockedUntil',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='Balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='CustomerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomerPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PermissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankApp.permission')),
            ],
        ),
    ]
