# Generated by Django 4.2.6 on 2023-11-01 10:24
from django.db import migrations, models
from django.contrib.auth.hashers import make_password
from BankApp.models import Customer, Account, Permission


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
    ]

    def insert(apps, schema_editor):
        pass1 = "squarepants"
        pass2 = "redqueen"

        f1 = "Bob"
        l1 = "Sponge"
        s1 = 101
        
        f2 = "Alice"
        l2 = "Queen"
        s2 = 102

        inititBal = 100.0
        inititBal2 = 0.0

        cust1 = apps.get_model('BankApp', 'Customer').objects.create(
            SocSecNumber = s1,
            FirstName = f1,
            LastName = l1,
            password = make_password(pass1)
        )
        cust2 = apps.get_model('BankApp', 'Customer').objects.create(
            Id= 2,
            SocSecNumber = s2,
            FirstName = f2,
            LastName = l2,
            password = make_password(pass2)
        )


        apps.get_model('BankApp', 'Account').objects.create(
            CustomerId= cust1,
            Name= "Bob's account",
            Balance= inititBal
        )
        apps.get_model('BankApp', 'Account').objects.create(
            CustomerId= cust2,
            Name= "Alice's account",
            Balance= inititBal
        )

        perm1 = apps.get_model('BankApp', 'Permission').objects.create(
            Id = 1,
            Code = "can_transfer"
        )

        apps.get_model('BankApp', 'CustomerPermissions').objects.create(
            CustomerId = cust1,
            PermissionId = perm1
        )
        apps.get_model('BankApp', 'CustomerPermissions').objects.create(
            CustomerId = cust2,
            PermissionId = perm1
        )


    operations = [
        migrations.RunPython(insert),
    ]
