# Generated by Django 4.2.6 on 2023-12-06 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0002_customer_socsecnumber2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountToName', models.CharField(max_length=20)),
                ('Amount', models.FloatField()),
                ('Message', models.CharField(max_length=200)),
                ('AccountFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionhistory_set_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
